services:
  go-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: go-app
    volumes:
      - ./go-app:/app  # Mount the local source code directory to the container
    ports:
      - "8080:8080"
    depends_on:
      - redis


  redis:
    image: redis:alpine
    container_name: redis-app
    ports:
      - "6379:6379"
    volumes:
      - url-serive-volume:/data  # Use a named volume for Redis data persistence

volumes:
  url-serive-volume:
