# Use the official Go image as the base image
FROM golang:alpine3.20 AS builder

# Set the Current Working Directory inside the container
WORKDIR /app/api

# Copy only the go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Run go mod tidy to clean up go.mod and go.sum
RUN go mod tidy

# Copy the source code into the container
COPY . .

# Install air for live reloading
RUN go install github.com/air-verse/air@latest

# Expose port 8080
EXPOSE 8080

# Start the application with air
CMD ["air", "-c", ".air.toml"]
